version: '3'
services:
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'